### ISSUE TITLE
Efficient use of CSG while animating ?

### ISSUE THREAD

**Issue by stuaxo** [timknip/pycsg#2]
I tried changing the example code to do the CSG during rendering, obviously this is quite slow, any ideas on how to do CSG in an animation efficiently ?

Ideally I'd like to be able to have some 3d object have slices moving through it (in response to audio)

**Comment by timknip** [comment]
Maybe better to create N meshes in some pre-process and animate these. 
ie: load the meshes into several GL buffers and then simply switch buffers on each frame.

Don't think CSG can be sped up alas.

**Comment by stuaxo** [comment]
That makes sense.

It's interesting how this code seems to run faster in python than pypy

Here's the example code, but with output to a .profile added
https://gist.github.com/stuaxo/091e1db7b1495061a2cd

I tried using "blist" instead of list (though this doesn't work in pypy), and adding '__slots__' to the classes in pycsg ... this gave a tiny speedup - but nothing notable -

```
real	0m3.608s
user	0m3.508s
sys	0m0.056s
```

```
real	0m3.626s
user	0m3.552s
sys	0m0.032s
```

I guess anything further might move things away from the nice architecture you have and make the code less understandable.

Better locality of could probably speed things up on the low level.   Batching operations, storing all the vertices in numpy arrays and batching operations might help.

This algorithm on realtime csg looks interesting, though it is only for convex shapes (not sure if it is possible to split concave ones into convex) -

http://sandervanrossen.blogspot.tw/2009/12/realtime-csg-part-1.html

Later on he changes from a btree to a sparse tree - this probably gets a speed up because of locality again.

**Comment by stuaxo** [comment]
Using pyrr might be interesting ... though whether it would be faster or slower than just swapping it in I don't know.

https://github.com/adamlwgriffiths/Pyrr

Looking at profiling data in runsnakerun - a lot of time is spent in constructors in geom -  17% compared to low level operations like lerp (5.8%) and dot (7%)
